name: Render

on:
  push:
    branches: [master]
  schedule:
    # Runs every Thursday at 20:23 UTC to avoid bit rot
    - cron: "20 23 * * 4"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Render list
        run: make render
      - uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          branch: ${{ github.head_ref }}
          commit_message: Commit list
          commit_user_name: GitHub Actions Bot
          commit_user_email: github-actions-bot@analysis-tools.dev
          commit_author: GitHub Actions Bot <github-actions-bot@analysis-tools.dev>
